FORMAT: 1A
HOST: twistory.pythonanywhere.com/

#### Twistory
Twistory API gives access to real world **Twitter data** and view _trending events_ 


# Group Handles
Twitter Handle resources are _people/entities_ that are actively engaged on twitter 

## Handle [/handles/{handles_id}]
  Handle object that represents data from a single profile
+ Parameters
    + handles_id (optional, string, `/handles/lebron_james`) ... Unique identifier to a twitter profile.

+ Model (application/json)
    + Headers

        ```
        Link: <http:/api.gistfox.com/>;rel="self",<http:/api.gistfox.com/gists>;rel="handles"
        ```
    + Body

        ```
        {
          "_links": {
              "self": { "href": "/" },
              "gists": { "href": "/gists?{since}", "templated": true }
          }
        }
        ```
        
### Retrieve a single Handle [GET]
+ Response 200 
    
    [Handle][]

## Handle Collection [/handles]
Retrieve a collection of Handles 
+ Model (application/json)
    + Headers

        ```
        Link: <http:/api.gistfox.com/>;rel="self",<http:/api.gistfox.com/gists>;rel="handles"
        ```
    + Body

        ```
        {
          "_links": {
              "self": { "href": "/" },
              "gists": { "href": "/gists?{since}", "templated": true }
          }
        }
        ```
        
### Retrieve a Collection of Handles [GET]
+ Response 200 
    
    [Handle Collection][]




# Group Hashtags
Hashtags are markers that denote a specific tweet

## HashTags Collection [/hashtags]
### List all HashTags [GET]
+ Response 200 (application/json)

        [{
         "id": 1, "name": "HeatsVsSpurs" retweet_count:"600000" 
        }, {
         "id": 2, "name": "WorldCup" retweet_count:"99999999"
        }]

### Create a Hashtag [POST]
+ Request (application/json)

        { "name": "LebronFreeAgency" }

+ Response 201 (application/json)

        { "id": 3, "name": "LebronnFreeAgency" }
       


## HashTag [/hashtags/name/]
Get all hashtags with a certain name

+ Parameters
   + name (required, string, `WorldCup` ) ... Need to be the name of objects
   
### Retrieve a Hashtag [GET]
+ Response 200 (application/json)

   + Header

            X-My-Header: The Value

   + Body

            { "id": 2, "name":"WorldCup" }


## HashTag [/hashtags/{id}]
A single Note object with all its details

+ Parameters
   + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.


### Retrieve a Hashtag [GET]
+ Response 200 (application/json)

   + Header

            X-My-Header: The Value

   + Body

            { "id": 2, "name":"WorldCup" }

### Remove a Hashtag [DELETE]
+ Response 204

