FORMAT: 1A
HOST: http://www.google.com

#### Twistory
Twistory API gives access to real world **Twitter data** and view _trending events_ 

# Group Handles
Twitter Handle resources are people/entities that are actively engaged on twitter 

## Handle Collection [/handles]
### List the id, tweeter identifier, and name of all Handle [GET]
+ Response 200 (application/json)

        [{
         "id": 1, "identifier": "KingJames","name": "Lebron James",
        }, {
         "id": 2, "identifier": "kobebryant","name": "Kobe Bryant"
        }]



## Detailed info of each id [/handles/{id}]

+ Parameters
    + id (required, integer) ... This is the id of the desired handle

    
### List all the info of the handle with the given id [GET]
+ Response 200 (application/json)

        [{
         "id": 1, "identifier": "KingJames", "name": "Lebron James", "profile picture": [link to profile picture], 
         "bio": "String content", "tweets": "website of the person's tweeter account", "Graphs": [link to graphs of some statistic ],
         "Video": [link to the featured video related to the handle], "related handles": "/handles/{id}/handles",
         "related hashtags": "/handles/{id}/hashtags", "related clusters": "/clusters/{id}/clusters"
        }]

## Related handles of each handle [/handles/{id}/handles]

+ Parameters
    + id (required, integer) ... This is the id of the desired handle

    
### List the id, tweeter identifier, name and this website's page of handles related to the handle of the given id [GET]
+ Response 200 (application/json)

        [{
         "id": 2, "identifier": "kobebryant", "name": "Kobe Bryant", "page": "/handles/{id}"
        }]

## Related hashtags of each handle [/handles/{id}/hashtags]

+ Parameters
    + id (required, integer) ... This is the id of the desired handle

    
### List the id, name and this website's page of hashtags related to the handle of the given id [GET]
+ Response 200 (application/json)

        [{
         "id": 1, "name": "HeatsVsSpurs", "page": "/hashtags/{id}"
        }]


## Related clusters of each handle [/handles/{id}/clusters]

+ Parameters
    + id (required, integer) ... This is the id of the desired handle

    
### List the id, name and this website's page of hashtags related to the handle of the given id [GET]
+ Response 200 (application/json)

        [{
         "id": 1, "name": "HeatsVsSpurs", "page": "/hashtags/{id}"
        }]


# Group Hashtags
Hashtags are markers that denote a specific tweet

## HashTags Collection [/hashtags]
### List all HashTags and all their info [GET]
+ Response 200 (application/json)

        [{
         "id": 1, "name": "HeatsVsSpurs", retweet_count:"600000" 
        }, {
         "id": 2, "name": "WorldCup", retweet_count:"99999999"
        }]


## HashTags Collection [/hashtags/id/i/tweeters]

+ Parameters
    + i (required, integer) ... this is the id of hashtags

### List the id and identifier of the handles that tweet a certain hashtag [GET]
+ Response 200 (application/json)

        [{
         "id": 1, "identifier": "KingJames"
         }, {
         "id": 2, "identifier": "kobebryant"
         }]




## HashTags Collection [/hashtags/name]
### List the names of all hashtag [GET]
+ Response 200 (application/json)

        [{
         "name": "HeatsVsSpurs" 
        }, {
         "name": "WorldCup"
        }]



## HashTag [/hashtags/name/n]
Get all hashtags with a certain name

+ Parameters
   + n (required, string, `WorldCup` ) ... Need to be the name of objects
   
### Retrieve a Hashtag [GET]
+ Response 200 (application/json)

   + Header

            X-My-Header: The Value

   + Body

            { "id": 2, "name":"WorldCup" }

## HashTag [/hashtags/id/i]
Get the hashtag info with a certain id

+ Parameters
   + i (required, integer, `1` ) ... Need to be an integer

   
### Retrieve a Hashtag [GET]
+ Response 200 (application/json)

   + Header

            X-My-Header: The Value

   + Body

            { "id": 2, "name":"WorldCup" }



## HashTag [/hashtags/{id}]
A single Note object with all its details

+ Parameters
   + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.


### Retrieve a Hashtag [GET]
+ Response 200 (application/json)

   + Header

            X-My-Header: The Value

   + Body

            { "id": 2, "name":"WorldCup" }



